### ISSUE TITLE
Reactive messaging guides no longer work after upgrading the kafka-client dependency to 2.6.0 

### ISSUE THREAD

**Issue by griffinhadfield** [OpenLiberty/open-liberty#15031]
When upgrading the `kafka-client` dependency in the Open Liberty Reactive Messaging guides from `2.4.0` to `2.6.0` the application no longer works. 

To reproduce the issue for the [Creating reactive Java microservices](https://openliberty.io/guides/microprofile-reactive-messaging.html) guide, you can update the `kafka-client` dependency in the `system/pom.xml` and the `inventory/pom.xml` and follow the steps of the guide. Once the containers are running, if you check the docker logs of the `system` container you can see the following error message: 
```
[ERROR  ] CWMRX1003E: An error occurred when sending a message to the Kafka broker. The error is: org.apache.kafka.common.errors.TimeoutException: Topic systemLoadTopic not present in metadata after 60000 ms.
```

To reproduce issue for the [Integrating RESTful services with a reactive system](https://openliberty.io/guides/microprofile-reactive-messaging-rest-integration.html) guide, you can again update the `kafka-client` dependency in the `system/pom.xml` and the `inventory/pom.xml` and follow the steps of the guide. In the docker logs of the `system` container you can see the following error message:

```
[ERROR   ] CWMRX1004E: The Reactive Messaging Kafka Outgoing Connector received an error. The error is java.util.concurrent.CompletionException: java.lang.NoClassDefFoundError: com.fasterxml.jackson.databind.JsonNode
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1005)
	at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2137)
	at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:110)
	at com.ibm.ws.microprofile.reactive.messaging.kafka.KafkaInput.lambda$createPublisher$2(KafkaInput.java:109)
	at [internal classes]
Caused by: java.lang.NoClassDefFoundError: com.fasterxml.jackson.databind.JsonNode
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.sendFindCoordinatorRequest(AbstractCoordinator.java:787)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.lookupCoordinator(AbstractCoordinator.java:269)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:236)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:485)
	at org.apache.kafka.clients.consumer.KafkaConsumer.updateAssignmentMetadataIfNeeded(KafkaConsumer.java:1268)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1230)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1210)
	at com.ibm.ws.microprofile.reactive.messaging.kafka.adapter.impl.KafkaConsumerImpl.poll(KafkaConsumerImpl.java:91)
	... 1 more
```

**Diagnostic information:**
 - OpenLiberty Version: 20.0.0.10
 - Java Version: OpenJDK 11.0.7

**Comment by Azquelt** [comment]
This looks related to https://issues.apache.org/jira/browse/KAFKA-10378

Pre-2.6.0, jackson-databind was an optional dependency but it looks like 2.6.0 started to require it without declaring it as a required dependency.

The fix in the linked PR appears to be to declare jackson-databind as a required dependency.

**Comment by tevans78** [comment]
@griffinhadfield We think this was fixed in Kafka Client version 2.6.1 and 2.7.0. Closing this issue but please let us know if there are any further issues.
