### ISSUE TITLE
Classpath visibility unclear -> NoClassDefFoundError: javax.cache.CacheException since 22.0.0.4 (maybe since 22.0.0.3)

### ISSUE THREAD

**Issue by AryonaOut** [OpenLiberty/open-liberty#20939]
Hello,

we do have a problem after updating from 22.0.0.2 (ok) to 22.0.0.4 (not ok) in combination with Hazelcast 5.1.1

We don't use JCache or HTTP-Sessions but use Hazelcast to keep a state across different K8S-Pods and requests.
With <=22.0.0.2 everything is ok (22.0.0.3 not tested yet), 22.0.0.4 fails and 22.0.0.5-beta fails, too.

The error message we get with 22.0.0.4 is quite simple:
```
Node creation failed 
java.lang.NoClassDefFoundError: javax.cache.CacheException
```
Apparently, Hazelcast trys to get a classloader for JCache and, if successful, registers some exceptions (which fails)
Hazelcast looks for (all)
- javax.cache.Caching
- javax.cache.integration.CacheLoaderException
- javax.cache.integration.CacheWriterException
- javax.cache.processor.EntryProcessorException
- javax.cache.configuration.CompleteConfiguration

If all are available, it tries to register **javax.cache.CacheException** but fails with NoClassDefFoundError.

Features in use:
- microProfile-5.0
- enterpriseBeansLite-4.0
- mail-2.0
- beanValidation-3.0

Classloader used to check for javax.cache.Caching etc. is (java.lang.ClassLoader)
`public Class<?> loadClass(String className) throws ClassNotFoundException { ... }`
and the caused NoClassDefFoundError happens by simply using "CacheException.class" after an (unsuccessful) "import javax.cache.CacheException;"

Since it is OK with older OpenLiberty versions like 22.0.0.2 we are not sure if there are some visibility issues regarding classloaders etc. and need some help figuring out what happens here

**Comment by jvanhill** [comment]
I did make some changes in one of those releases as we binary transform the JCache API JAR when running with EE9 since it depends on the `javax.enterprise` for its annotations, which aren't available in EE9 (they are now `jakarta.enterprise`). However; the JCache packages (`javax.cache.*`) are only exposed when using sessionCache-1.0 feature.

Do you provide the JCache API jar for your application or do you expect Liberty to provide the `javax.cache` classes?

EDIT - I should clarify that we have been transforming the JCache jar since we GA'd EE9. I have made a few changes for upcoming JCache support for another feature I am working on that went into one of those releases. However; they *should* not effect you unless using sessionCache-1.0 (key word being should).

**Comment by AryonaOut** [comment]
sessionCache-1.0 is definitely disabled, we don't enable it within the features and it isn't listed upon server start (where the activated features show up)

We don't use JCache so we don't provide an API.jar for this and we do expect this to be turned off so it cannot be detected like Hazelcast does it (or, at least, having a trigger to disable it).

As stated above, javax.cache.Caching is found but javax.cache.CacheException is not so something is quite different than before.

**Comment by jvanhill** [comment]
@AryonaOut - Hazelcast is a JCache provider, so perhaps even when not using the JCache functionality, there may be some dependencies. I assume you were running with EE9 before and after - the test runs are identical except for the version of Liberty?

Can you post the entire stack trace of the error? Maybe that will give us some insight.

**Comment by AryonaOut** [comment]
@jvanhill We did use Jakarta 9 before, OL 22.0.0.2, this is still ok.
We run exactly the same system, same OS etc, just updated from 22.0.0.2 to 22.0.0.4

```
Node creation failed\njava.lang.NoClassDefFoundError: javax.cache.CacheException
	at com.hazelcast.client.impl.protocol.ClientExceptionFactory.<init>(ClientExceptionFactory.java:225)
	at com.hazelcast.client.impl.ClientEngineImpl.initClientExceptionFactory(ClientEngineImpl.java:148)
	at com.hazelcast.client.impl.ClientEngineImpl.<init>(ClientEngineImpl.java:134)
	at com.hazelcast.instance.impl.Node.<init>(Node.java:260)
	at com.hazelcast.instance.impl.HazelcastInstanceImpl.createNode(HazelcastInstanceImpl.java:149)
	at com.hazelcast.instance.impl.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:118)
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:217)
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.getOrCreateHazelcastInstance(HazelcastInstanceFactory.java:114)
	at com.hazelcast.core.Hazelcast.getOrCreateHazelcastInstance(Hazelcast.java:169)
```
The deployed WAR-file only has hazelcast.jar as single lib included, we use (as stated above) the IMDG to synchronize cached data between different pods (NO http-sessions etc., only cached Strings/Integers... to be shared between pods)

If it helps:
https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/cache/impl/JCacheDetector.java
The method in Line #82 returns false for 22.0.0.2 but true for 22.0.0.4

The exception then occurs because of line #225 in
https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/client/impl/protocol/ClientExceptionFactory.java

**It looks like 22.0.0.4 provides a cache-api but 22.0.0.2 has no provided cache-api (comments in JCacheDetector)**

server.xml
```
<?xml version="1.0" encoding="UTF-8"?>
<server description="Microservice">
  <featureManager>
    <feature>microProfile-5.0</feature>
    <feature>beanValidation-3.0</feature>
  </featureManager>
  <httpEndpoint host="*" httpPort="9080" httpsPort="9443" id="defaultHttpEndpoint" />
  <mpJwt ... />
  <mpMetrics ... />
  <cors ... />
  <logging ... />
  <applicationManager ... />
  <applicationMonitor ... />
  <webApplication id="microservice" name="microservice" location="/liberty/microservice.war" contextRoot="${context_root}" />
</server>
```
Installed features (log):
appSecurity-4.0, beanValidation-3.0, cdi-3.0, concurrent-2.0, distributedMap-1.0, expressionLanguage-4.0, jndi-1.0, json-1.0, jsonb-2.0, jsonp-2.0, jwt-1.0, localConnector-1.0, microProfile-5.0, monitor-1.0, mpConfig-3.0, mpFaultTolerance-4.0, mpHealth-4.0, mpJwt-2.0, mpMetrics-4.0, mpOpenAPI-3.0, mpOpenTracing-3.0, mpRestClient-3.0, restfulWS-3.0, restfulWSClient-3.0, servlet-5.0, ssl-1.0, transportSecurity-1.0

**Comment by dazavala** [comment]
Hello @AryonaOut.  [edited] I believe the server, configured with features microProfile-5.0 and beanValidation-3.0, is making the javax.cache package visible to the application's thread classloading context.  Hazelcast eventually attempts to load the javax.cache.Cache using the thread context loader.  I suspect the load succeeds.  Then I suspect Hazelcast uses the application classloader to load class javax.cache.CacheException, which fails with CNFE and causes the NCDFE.  A [classloading mustgather diagnostic](https://www.ibm.com/support/pages/mustgather-classloader-problems-websphere-application-server-liberty-profile) will help verify my theory as it will tell us the code source(s) and the load behaviors for the javax.cache classes along with the server's introspection data. 

Would please run and upload the diagnostic?  The mustgather procedure is straightforward: enable classloading trace on the server, stop the server, clear the server logs, start the server with the --clean option, dump the server, then upload the resulting server dump (zip) file to this issue.  The server dump file will contain the trace and introspection data.

Or, please open a support case with IBM and we'll work though the diagnostic mustgather and resolution for this issue.

**Comment by AryonaOut** [comment]
@dazavala did as you requested (but had to remove the actual application)
Hopefully this will help solve this issue.

**Comment by AryonaOut** [comment]
@dazavala did as you requested (but had to remove the actual application and since it has 30MB I had to split it up and due to restrictions I had to rename ...zip.001 to 001.zip and ...zip.002 to 002.zip)
Hopefully this will help solve this issue
[afab-ks1.dump-22.05.11_09.44.55-001.zip](https://github.com/OpenLiberty/open-liberty/files/8667881/afab-ks1.dump-22.05.11_09.44.55-001.zip)
[afab-ks1.dump-22.05.11_09.44.55-002.zip](https://github.com/OpenLiberty/open-liberty/files/8667889/afab-ks1.dump-22.05.11_09.44.55-002.zip)
.

**Comment by dazavala** [comment]
@AryonaOut Thanks for the diagnostics. The javax.cache packages are now (unexpectedly) visible to the application's thread classloading context, which causes Hazelcast to determine JCache is available. But, the packages are not visible to the application (as expected). We know why and are looking into potential resolutions. I don't have a workaround to offer you.

**Comment by AryonaOut** [comment]
@dazavala if this will be fixed in the next releases that would be sufficient, at least for me.
thanks for your support

**Comment by jvanhill** [comment]
I have added a FVT that reproduces the issue in PR #21227.

**Comment by michael-water** [comment]
Hi,
I have the same problem with WebSphere Liberty 22.0.0.6.
Is there any ETA for the fix?
Thanks.

**Comment by jvanhill** [comment]
I have delivered a fix for this and it should make it out in the 22008 release. I am working on an interim fix, but I don't have an ETA for it.

For clarification, I should also be clear that the root of the NoClassDefFoundException is due to Hazelcast's inconsistent loading of classes. The problem is that they use the thread context classloader (TCCL) to determine if JCache is available (are the javax.cache classes available). We did make a change that exposed the issue since some of the javax.cache classes were being loaded into the TCCL. In the fix, we will only expose them in the TCCL when necessary, but even with the fix, it is possible you will still see this as we must expose those classes in the TCCL in some instances.

- They check if JCache is available in ClientEngineImpl here:
  - https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/client/impl/ClientEngineImpl.java#L147

- Within the above call, they eventually check for the class in the TCCL here:
  - https://github.com/hazelcast/hazelcast/blob/77ff44a418677038a7889e16ab464850e645849e/hazelcast/src/main/java/com/hazelcast/internal/nio/ClassLoaderUtil.java#L257

- The problem is that then in ClientExceptionFactory, they don't check the TCCL when try to register the javax.cache classes. This is inconsistent behavior.
  - https://github.com/hazelcast/hazelcast/blob/77ff44a418677038a7889e16ab464850e645849e/hazelcast/src/main/java/com/hazelcast/client/impl/protocol/ClientExceptionFactory.java#L225

A true fix for this issue should be made by Hazelcast to make checking whether the JCache classes are available and the registering of those JCache classes in ClientExceptionFactory consistently use (or not use) the TCCL.

**Comment by jvanhill** [comment]
I am closing this issue so that it can be recorded in the 22008 release as being fixed.

However; I am currently working on interim fixes for back-level versions.

**Comment by krismarc** [comment]
Hi @jvanhill,

we would be interested in your interim fix. How could we track this if this issue is closed? No offense, maybe I am not aware of good source of this information.

btw, do you know if regular liberty is also affected with the same? 

Best regards,
K.M.

**Comment by jvanhill** [comment]
@krismarc - To receive an interim fix, you must open a ticket with IBM support.
