### PR TITLE
Revert PR #21521 (unrevert PR #21263).

### LINKED ISSUE #20939: Classpath visibility unclear -> NoClassDefFoundError: javax.cache.CacheException since 22.0.0.4 (maybe since 22.0.0.3)
Hello,

we do have a problem after updating from 22.0.0.2 (ok) to 22.0.0.4 (not ok) in combination with Hazelcast 5.1.1

We don't use JCache or HTTP-Sessions but use Hazelcast to keep a state across different K8S-Pods and requests.
With <=22.0.0.2 everything is ok (22.0.0.3 not tested yet), 22.0.0.4 fails and 22.0.0.5-beta fails, too.

The error message we get with 22.0.0.4 is quite simple:
```
Node creation failed 
java.lang.NoClassDefFoundError: javax.cache.CacheException
```
Apparently, Hazelcast trys to get a classloader for JCache and, if successful, registers some exceptions (which fails)
Hazelcast looks for (all)
- javax.cache.Caching
- javax.cache.integration.CacheLoaderException
- javax.cache.integration.CacheWriterException
- javax.cache.processor.EntryProcessorException
- javax.cache.configuration.CompleteConfiguration

If all are available, it tries to register **javax.cache.CacheException** but fails with NoClassDefFoundError.

Features in use:
- microProfile-5.0
- enterpriseBeansLite-4.0
- mail-2.0
- beanValidation-3.0

Classloader used to check for javax.cache.Caching etc. is (java.lang.ClassLoader)
`public Class<?> loadClass(String className) throws ClassNotFoundException { ... }`
and the caused NoClassDefFoundError happens by simply using "CacheException.class" after an (unsuccessful) "import javax.cache.CacheException;"

Since it is OK with older OpenLiberty versions like 22.0.0.2 we are not sure if there are some visibility issues regarding classloaders etc. and need some help figuring out what happens here

### LINKED ISSUE #21522: Re-introduce change reverted from 21263
Re-introduce change reverted from https://github.com/OpenLiberty/open-liberty/pull/21263

### LINKED ISSUE #22007: Spring boot 2.3.4 application stops on wlp 22.0.0.7
Hi, 

I have recently upgraded the liberty server from 21.0.0.12 to 22.0.0.7
After this my spring boot application has stopped starting.
I am getting below error on startup. Incident files attached for reference.

 :: Spring Boot ::        (v2.3.4.RELEASE)
2022-08-06 18:54:19.440  INFO 11272 --- [ecutor-thread-4] c.hsbc.ccoonboarding.ServletInitializer  : Starting ServletInitializer on LPT3802 with PID 11272 (D:\Softwares\wlp8-22.0.0.7\usr\servers\defaultServer\apps\expanded\cco-onboarding.war\WEB-INF\classes started by saurabhsingh in D:\Softwares\wlp8-22.0.0.7\usr\servers\defaultServer)
2022-08-06 18:54:19.440 DEBUG 11272 --- [ecutor-thread-4] c..ccoonboarding.ServletInitializer  : Running with Spring Boot v2.3.4.RELEASE, Spring v5.2.9.RELEASE
2022-08-06 18:54:19.440  INFO 11272 --- [ecutor-thread-4] c..ccoonboarding.ServletInitializer  : The following profiles are active: ldap,mail,common
18:54:21,640 |-INFO in ch.qos.logback.classic.servlet.LogbackServletContextListener@40d3c251 - About to stop ch.qos.logback.classic.LoggerContext [default]
[ERROR   ] SRVE0285E: Exception caught while destroying context: java.lang.NullPointerException
	at org.jboss.weld.module.web.servlet.WeldInitialListener.contextDestroyed(WeldInitialListener.java:113)
	at [internal classes]
[ffdc_22.08.06_18.54.21.1.log](https://github.com/OpenLiberty/open-liberty/files/9275110/ffdc_22.08.06_18.54.21.1.log)
[exception_summary_22.08.06_18.54.16.0.log](https://github.com/OpenLiberty/open-liberty/files/9275111/exception_summary_22.08.06_18.54.16.0.log)

[AUDIT   ] CWWKZ0012I: The application cco-onboarding was not started.
[AUDIT   ] CWWKT0017I: Web application removed (default_host): http://localhost:9080/onboarding/

### PR DESCRIPTION
**Pull request by jvanhill**
This PR is to unrevert PR #21263, as it was backed out since the re-baseline of the feature verifier servers (from 22003 to 22006) removed exceptions for these changes from the ignore.xml files.

Fixes #20939
Fixes #21522
Fixes #22007

### CODE REVIEW

**Comment by jvanhill** [comment]
Need to wait to merge until the feature verifier changes make it to release in WS-CD-Open.

**Review by dazavala — APPROVED** [review]
Approved.  The product changes look good.  There are changes to two test files that do not appear in the reverted commit: LoggedOutCookiedCache.java, hazelcast-localhost-only.xml.  I've no reason to exclude either change.

**Comment by jvanhill** [comment]
#build
#libby

**Comment by jvanhill** [comment]
#build

**Comment by jvanhill** [comment]
One of the child builds (f4) was unable to contact RTC. Respun the build. There were no test failures.

https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_yoXGIPbeEey3m9ea3wJj4A

**Comment by jvanhill** [comment]
#build
#libby
